CREATE TABLE "game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "koTitle" varchar UNIQUE NOT NULL,
  "enTitle" varchar,
  "cnTitle" varchar,
  "jpTitle" varchar,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "game_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "gameId" integer UNIQUE NOT NULL,
  "url" text NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "game_setting" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "gameId" integer UNIQUE NOT NULL,
  "devCorp" varchar NOT NULL,
  "relatedUrl" jsonb,
  "storeUrl" jsonb,
  "setting" jsonb,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "character" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "gameId" integer UNIQUE NOT NULL,
  "isNew" bool DEFAULT false,
  "isReleased" bool DEFAULT false,
  "isProgress" bool DEFAULT false,
  "element" varchar,
  "name" varchar NOT NULL,
  "path" varchar,
  "rarity" varchar,
  "ratings" jsonb,
  "stats" jsonb,
  "tierCategory" varchar,
  "tierListNew" bool DEFAULT false,
  "tierListTags" text,
  "voiceActors" jsonb,
  "releaseDate" date,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "character_details" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "characterId" integer UNIQUE NOT NULL,
  "stats" jsonb,
  "ascensionMaterials" jsonb,
  "buildData" jsonb,
  "builderInfoData" jsonb,
  "itemData" jsonb,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "character_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "characterId" integer UNIQUE NOT NULL,
  "backgroundColor" varchar NOT NULL DEFAULT '#ffffff',
  "layout" varchar,
  "url" text NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "characterId" integer NOT NULL,
  "gameId" integer NOT NULL,
  "info" varchar,
  "element" varchar,
  "name" varchar NOT NULL,
  "desc" jsonb,
  "path" varchar,
  "rarity" varchar,
  "levelData" jsonb,
  "itemReferences" jsonb,
  "skillId" integer,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "item_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "itemId" integer UNIQUE NOT NULL,
  "backgroundColor" varchar NOT NULL DEFAULT '#ffffff',
  "layout" varchar,
  "url" text NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "skill" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "gameId" integer NOT NULL,
  "info" varchar,
  "element" varchar,
  "name" varchar NOT NULL,
  "desc" jsonb,
  "path" varchar,
  "levelData" jsonb
);

CREATE TABLE "skill_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "skillId" integer UNIQUE NOT NULL,
  "backgroundColor" varchar NOT NULL DEFAULT '#ffffff',
  "layout" varchar,
  "url" text NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

ALTER TABLE "game" ADD FOREIGN KEY ("id") REFERENCES "game_image" ("gameId");

ALTER TABLE "game" ADD FOREIGN KEY ("id") REFERENCES "game_setting" ("gameId");

ALTER TABLE "character" ADD FOREIGN KEY ("gameId") REFERENCES "game" ("id");

ALTER TABLE "character_image" ADD FOREIGN KEY ("characterId") REFERENCES "character" ("id");

ALTER TABLE "character" ADD FOREIGN KEY ("id") REFERENCES "character_details" ("characterId");

ALTER TABLE "item" ADD FOREIGN KEY ("gameId") REFERENCES "game" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("characterId") REFERENCES "character" ("id");

ALTER TABLE "item_image" ADD FOREIGN KEY ("itemId") REFERENCES "item" ("id");

ALTER TABLE "skill" ADD FOREIGN KEY ("gameId") REFERENCES "game" ("id");

ALTER TABLE "skill_image" ADD FOREIGN KEY ("skillId") REFERENCES "skill" ("id");
